version: 1.0

phase:
 install:
  runtime-versions:
   java: corretto8
  pre_build:
   -echo Nothing to do in pre_build phase...
  build:
   commands:
    - echo Build started on `date`
    - mvn install
  post_build:
   command:
    - echo Build completed on `date`
  artifacts:
   - target/SampleRestApplication-0.0.1-SNAPSHOT.jar
